# Generated by Django 5.2.6 on 2025-09-23 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em Andamento'), ('FN', 'Finalizada'), ('CA', 'Cancelada')], default='AB', max_length=2)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Soma dos preços dos serviços', max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_de_servico', to='api.cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_de_servico', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ManyToManyField(to='api.servico')),
            ],
        ),
    ]
