# Generated by Django 5.2.6 on 2025-09-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordemdeservico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemdeservico',
            old_name='servico',
            new_name='servicos',
        ),
    ]
