# Generated by Django 5.2.6 on 2025-09-23 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_servico_ordemdeservico_servicos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordemdeservico')),
            ],
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='materiais',
            field=models.ManyToManyField(through='api.MaterialUtilizado', to='api.material'),
        ),
    ]
