# Generated by Django 5.2.6 on 2025-09-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ordemdeservico_valor_total_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialutilizado',
            name='ordem_de_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_utilizados', to='api.ordemdeservico'),
        ),
    ]
