# Generated by Django 5.2.6 on 2025-10-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_materialutilizado_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em Andamento'), ('FN', 'Finalizada'), ('PG', 'Paga'), ('CA', 'Cancelada')], default='AB', max_length=2),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DIN', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('BOL', 'Boleto')], max_length=3)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.ordemdeservico')),
            ],
        ),
    ]
