# Generated by Django 5.2.6 on 2025-10-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_ordemdeservico_status_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ponto_referencia",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
