# Generated by Django 5.2.6 on 2025-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_cliente_observacoes_cliente_ponto_referencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="unidade_medida",
            field=models.CharField(blank=True, default="un", max_length=20),
        ),
    ]
