# Generated by Django 5.2.6 on 2025-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_material_unidade_medida"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdeservico",
            name="data_agendamento",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="endereco_servico",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
