# Generated by Django 5.2.6 on 2025-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ordemdeservico_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='duracao_estimada_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Duração Estimada (em horas)'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Agendamento'),
        ),
    ]
