# Generated by Django 5.2.6 on 2025-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ordemdeservico_duracao_estimada_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='loja',
            field=models.CharField(blank=True, default='', help_text='Loja onde o material foi comprado', max_length=100),
        ),
    ]
