# Generated by Django 5.2.6 on 2025-11-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_material_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialutilizado',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.material'),
        ),
    ]
